### ISSUE TITLE
The -w and --write options should default to the 'all' option.

### ISSUE THREAD

**Issue by pansapiens** [serine/litlog#2]
So that `litlog -w` would be equivalent to `litlog -w A`.

Invalid options (like `litlog -w X` or `litlog --write a`) should print an error message to stderr.

**Comment by serine** [comment]
I'm not sure about this just now. It makes sense to have all as a default value. But I want user to think what he/she is writting out, hence no default for now. It is likely that something will become a default value

Thanks though
